---
title: "Technical stuff"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Calculation of confidence bands 
Pointwise CI for fitted curve: Obtained from fitted curve $\hat\eta = \beta_0+ \beta_1 \underbrace{\cdot x^{p_1}}_{=:w_1}+\beta_2\cdot \underbrace{\begin{cases} x^{p_2}, p_2 \neq p_1\\ x^{p_1}\cdot \log(x), p_2 = p_1 \end{cases}}_{=:w_2}$ ($p_1, p_2 \in \{−2,−1,−0.5, 0, 0.5, 1, 2, 3\}$ with power = 0 equals the natural log
of x) as $\hat\eta \pm z_{1-\alpha/2} \cdot SE(\hat\eta)$ where $z_{1-\alpha/2}$ is the $100\cdot(1-\alpha)$th percentile of the normal distribution. 


The SE of $\hat\eta_i$ is calculated by: 
\begin{align*} var(\hat\eta_i)=var(\hat\beta_0)+var(\hat\beta_1)w_{1i}^2+var(\hat\beta_2)w_{2i}^2+2cov(\hat\beta_0\hat\beta_1)w_{1i}+2cov(\hat\beta_0\hat\beta_2)w_{2i}+2cov(\hat\beta_1\hat\beta_2)w_{1i}w_{2i} \end{align*} 
and var$(\hat\beta) = \hat\sigma^2(X^TX)^{-1}$ where $\hat\sigma^2 = \frac{1}{n}\sum_i (\hat\eta_i-y_i)^2$ and  
\begin{align*} X = 
\left( \begin{array}{rrr} 
1 & w_{11} & w_{21} \\ 
1 & w_{12} & w_{22} \\ 
\vdots & \vdots & \vdots \\ 
1 & w_{1n} & w_{2n} \\ 
\end{array} \right)
=
\left( \begin{array}{rrr} 
1 & x_1^{p_1} & \begin{cases} x_1^{p_2}, p_2 \neq p_1\\ x_1^{p_1}\cdot \log(x_1), p_2 = p_1 \end{cases} \\ 
1 & x_2^{p_1} & \begin{cases} x_2^{p_2}, p_2 \neq p_1\\ x_2^{p_1}\cdot \log(x_2), p_2 = p_1 \end{cases} \\ 
\vdots & \vdots & \vdots \\ 
1 & x_n^{p_1} & \begin{cases} x_n^{p_2}, p_2 \neq p_1\\ x_3^{p_1}\cdot \log(x_n), p_2 = p_1 \end{cases} \\ 
\end{array} \right) \end{align*}
